# Generated by Django 6.0 on 2025-12-16 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sector 1-10, RIICO Industrial Area', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='locations.location')),
            ],
            options={
                'db_table': 'service_areas',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=255)),
                ('experience', models.CharField(choices=[('LESS_THAN_1', 'Less than 1 year'), ('1_TO_3', '1-3 years'), ('3_TO_5', '3-5 years'), ('5_TO_10', '5-10 years'), ('MORE_THAN_10', 'More than 10 years')], max_length=20)),
                ('business_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('service_description', models.TextField()),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to='provider_docs/aadhaar/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to='provider_docs/aadhaar/')),
                ('address_proof_type', models.CharField(blank=True, choices=[('ELECTRICITY_BILL', 'Electricity Bill'), ('WATER_BILL', 'Water Bill'), ('RENT_AGREEMENT', 'Rent Agreement'), ('PROPERTY_TAX', 'Property Tax Receipt'), ('BANK_STATEMENT', 'Bank Statement')], max_length=30, null=True)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='provider_docs/address/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='provider_docs/photos/')),
                ('skill_certificate', models.FileField(blank=True, null=True, upload_to='provider_docs/certificates/')),
                ('application_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.location')),
                ('service_areas', models.ManyToManyField(related_name='providers', to='providers.servicearea')),
                ('service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'is_captain': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly Plan'), ('YEARLY', 'Yearly Plan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_slots', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='providers.serviceprovider')),
            ],
            options={
                'db_table': 'provider_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='providers.servicecategory')),
            ],
            options={
                'db_table': 'service_types',
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.servicetype'),
        ),
    ]
