# Generated by Django 5.1.3 on 2026-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_governmentservice_servicequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(related_name='providers', to='providers.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_types',
            field=models.ManyToManyField(related_name='providers', to='providers.servicetype'),
        ),
    ]
