# Generated by Django 5.1.3 on 2026-02-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_serviceprovider_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_english', models.TextField()),
                ('answer_hindi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='providers.servicequestion')),
            ],
            options={
                'verbose_name': 'Service Question Answer',
                'verbose_name_plural': 'Service Question Answers',
            },
        ),
    ]
