# Generated by Django 5.1.3 on 2026-02-05 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_servicequestionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pricings', to='providers.serviceprovider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_pricings', to='providers.servicetype')),
            ],
            options={
                'db_table': 'service_pricing',
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
