# Generated by Django 5.1.3 on 2026-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_servicepricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_docs/verification/'),
        ),
    ]
