# Generated by Django 5.1.3 on 2026-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='captain_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
