# Generated by Django 5.1.3 on 2026-02-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_captain_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CaptainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_front', models.ImageField(upload_to='captain_docs/aadhaar/')),
                ('aadhaar_back', models.ImageField(upload_to='captain_docs/aadhaar/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_captains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captain Profile',
                'verbose_name_plural': 'Captain Profiles',
                'db_table': 'captain_profiles',
            },
        ),
    ]
