# Generated by Django 5.1.3 on 2026-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_admin_verified_captainprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider_register',
            field=models.BooleanField(default=False),
        ),
    ]
